export const Recipes = [
  {
    title: 'Hamur Kızartması Tarifi Yapılışı',
    date: '01 Ocak 2018, Perşembe',
    recipeAuthor: 'Kodluyoruz',
    likeCount: 190,
    img: 'https://i.nefisyemektarifleri.com/2021/06/04/hamur-kizartmasi-1.jpg',
    description: [
      'Öncelikle derin bir kabın içinde bütün malzemeleri güzelce karıştırın ve alabildiğince un ekleyerek kulak memesi yumuşaklığında bir hamur oluşturun.',
      'Hamuru oklava yardımı ile çok ince ve çok kalın olmayacak şekilde (yaklaşık yarım cm kalınlığında) açınız.',
      'Açtığımız hamuru bıçak yardımı ile iki cm genişliğinde uzun parçalara bölün (resimde ki gibi )ve kabarması için bol, kızgın yağda kızartın.Deneyecek olanlara şimdiden afiyet olsun 😋😋😋.',
    ],
  },
  {
    title: 'Tek Başına Doyuran Tavuklu Şehriye Salatası Tarifi Yapılışı',
    date: '12 Ocak 2021, Salı',
    recipeAuthor: 'Kodluyoruz',
    likeCount: 145,
    img: 'https://i.nefisyemektarifleri.com/2021/06/04/tavuklu-arpa-sehriye-salatasi-6.jpg',
    description: [
      'Ocağa aldığımız uygun bir tencere içerisine sıvı yağımızı alalım ve içerisine arpa şehriyemizi ekleyerek güzelce kavuralım. Bu sırada daha hızlı olması için tavuğumuzu da tencereye alarak haşlayabiliriz.',
      'Ardından suyu ekleyip tuzunu ayarlayarak şehriyeler yumuşayıp suyunu çekene kadar pişirelim.',
      'Şehriyelerimiz piştikten sonra süzgece alalım ve soğuk sudan geçirelim, suyunun süzülmesi için bir kenarda bekletelim.',
      'Bir taraftan da haşlanan tavuğumuzu didikleyelim. Közlenmiş kırmızı biber ve kornişon turşularımızı da küçük küçük doğrayalım.',
      'Suyu süzülen arpa şehriyemizi uygun bir karıştırma kabı içerisine alalım ve üzerine göğüs eti, konserve mısır, doğradığımız kırmızı biber ve turşu, dereotu, limon suyu, zeytinyağı ve tuzu da ekleyerek güzelce karıştıralım.',
      'Ardından salatamızı uygun bir servis tabağına alıp üzerini limon dilimleri ile süsleyerek servis edelim. Afiyet olsun!',
    ],
  },
  {
    title: 'Lezzetli Ve Pratik Kaşık Tatlısı Tarifi Yapılışı',
    date: '2 Haziran 2020, Salı',
    recipeAuthor: 'Kodluyoruz',
    likeCount: 99,
    img: 'https://i.nefisyemektarifleri.com/2020/12/30/yedikce-yediren-kasik-tatlisi.jpg',
    description: [
      'Muhallebi için 4 yemek kaşığı un, 8 yemek kaşığı toz şeker ve 1 litre sütü sürekli karıştırarak pişiriyoruz.',
      'Kıvam tutmaya başlarken 1 paket şekerli vanilin (5 gr) ve 2 yemek kaşığı tereyağını ekleyip birkaç dakika daha pişirip göz göz olunca ocaktan alıyoruz.',
      'Ocaktan aldığımız muhallebiyi soğumadan servis kabına döküp ılımaya bırakıyoruz.',
      'Supangle için 750 ml süt, 2 yemek kaşığı mısır nişastası, 1 yemek kaşığı un, 3 yemek kaşığı toz şeker ve 3 yemek kaşığı kakaoyu iyice çırpıp pişiriyoruz.',
      'Pişen supangleyi ocaktan alıp muhallebinin üzerine ekleyip kakao ve çikolata ile süslüyoruz. Afiyet olsun 🥰.',
    ],
  },
  {
    title: 'Saray Sarması',
    date: '15 Eylül 2018, Cuma',
    recipeAuthor: 'Kodluyoruz',
    likeCount: 101,
    img: 'https://i.nefisyemektarifleri.com/2021/06/04/saray-sarmasitam-olcusu-ile.jpg',
    description: [
      'İlk olarak tepsinin tabanını hindistan cevizi ile kaplayalım(dilerseniz tepsiye folye serip yapabilirsiniz).',
      'Muhallebisi için süt, un, şeker, vanilya ve kakaoyu tencereye alıp pürüzsüz olacak şekilde karıştıralım.',
      'Ocağı açalım sürekli karıştırarak göz göz oluncaya kadar pişirelim.',
      'Ocağı kapatıp tereyağını ekleyelim ve eriyene kadar karıştıralım henüz muhallebi sıcakken tepsiyi kapladığımız hindistan cevizi üzerine eşit şekilde döküp spatula ile düzgünleştirelim ve soğuması için bir kenara kaldıralım.',
      'Krem şanti ve sütü mikserin yüksek devrinde çırpalım ve soğuyan kakaolu muhallenin üzerini eşit gelecek şekilde kaplayalım.',
      'Bu şekilde 1 saat buzdolabında bekletelim.',
      'Kestiğimiz bir dilimi düzgünce ve yavaşça spatula ile rulo şeklinde saralım ve tepsinin tabanında kalan hindistan cevizini üzerine yanlarına serpelim.',
      'Bu şekilde bütün dilimleri hazırlayıp servis tabağına alalım ve üzerini dilediğimiz gibi süsleyelim. Deneyecek arkadaşlarıma afiyet olsun ❣️',
    ],
  },
  {
    title: 'Kebab',
    date: '12 Nisan 2019, Cuma',
    recipeAuthor: 'Kodluyoruz',
    likeCount: 12,
    img: 'https://i.nefisyemektarifleri.com/2021/06/02/mantarli-et-sote-tarifi-5.jpg',
    description: [
      'İlk olarak tavamızı ocağa alarak ısıtalım. Ardından kuşbaşı etlerimizi tavaya alalım ve tavamızın kapağını kapatarak suyunu salıp çekene kadar önce yüksek ateşte ardından kısık ateşte ara ara karıştırarak pişirelim. Eğer etleriniz pişmemişse çok az daha sıcak su ilave ederek pişirmeye devam edebilirsiniz.',
      'Suyunu çeken etlerin üzerine sıvı yağı, yemeklik doğradığımız soğanı, yeşil biberi, kırmızı biberi ilave edelim ve ara ara karıştırarak orta ateşte sebzelerin diriliği gidene kadar kavuralım.',
      'Daha sonra domates salçası, karabiber, pul biber, kimyon ve kekiği ilave edip kavurmaya devam edelim.',
      'Sıcak suyumuzu da ilave edelim ve tekrar karıştıralım.',
      'Limonlu su içerisinde beklettiğimiz mantarlarımızı da doğrayalım ve tavamıza ilave ederek karıştıralım. Ardından tavamızın kapağını kapatalım ve mantarlar yumuşayana kadar ara ara karıştırarak pişirelim. Daha sulu etli mantar sote yapmak için az daha sıcak su ilave edebilirsiniz.',
      'Yemeğimiz güzelce piştikten sonra tuzumuzu da ekleyelim, 1-2 tur daha karıştırarak ocağı kapatalım. Etli mantar sotemiz servise hazır. Afiyet olsun.',
    ],
  },
];
